name: Claim Summary Function App
on:
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_NAME: 'FUNCTION_APP_NAME'
  RESOURCE_GROUP: 'RESOURCE_GROUP'
  FUNCTION_APP_PATH: './func app'
  BUILD_PACKAGE_NAME: 'functionapp.zip'
jobs:
  azure-login:
    runs-on: [self-hosted, Linux, x64]
    environment: ppd
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: 'Login to Azure'
        uses: wsib-eai/azure-login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

  build-az-function:
    needs: [azure-login]
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: 'Build Function App Package'
        working-directory: './func app'
        run: |
          zip -r ../${{ env.BUILD_PACKAGE_NAME }} . -x "__pycache__/*" "*.pyc"
  deploy-az-function:
    needs: [build-az-function]
    runs-on: [self-hosted, Linux, x64]
    environment: ppd
    steps:
      - name: 'Deploy Azure Function'
        uses: wsib-cbia/azure-functions-action@v1 // need to check if exists
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.BUILD_PACKAGE_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}//need to create
