name: Claim Summary Function App
on:
  workflow_dispatch:
env:
  PYTHON_VERSION: 'some version,Need to ask nataliia'
  AZURE_FUNCTIONAPP_NAME: 'FUNCTION_APP_NAME'
  RESOURCE_GROUP: 'RESOURCE_GROUP'
  FUNCTION_APP_PATH: './func app'
  BUILD_PACKAGE_NAME: 'functionapp.zip'
jobs:
  azure-login-setup:
    runs-on: [self-hosted, Linux, x64]
    environment: ppd
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: 'Login to Azure'
        uses: wsib-cbia/azure-login@v1 // need to check
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Install Python Dependencies'
        working-directory: './func app'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'Build Function App Package'
        working-directory: './func app'
        run: |
          zip -r ../${{ env.BUILD_PACKAGE_NAME }} . -x "__pycache__/*" "*.pyc"
  deploy-az-function:
    needs: [azure-login-setup]
    runs-on: [self-hosted, Linux, x64]
    environment: ppd
    steps:
      - name: 'Deploy Azure Function'
        uses: wsib-cbia/azure-functions-action@v1 // need to check if exists
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.BUILD_PACKAGE_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}//need to create
